"""LangGraph planner/tool loop powered by NVIDIA NIM."""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from datetime import date
from functools import lru_cache
from typing import Annotated, Any, TypedDict
from uuid import uuid4

import httpx
from langchain_core.messages import AIMessage, AnyMessage, HumanMessage, SystemMessage
from langchain_nvidia_ai_endpoints import ChatNVIDIA
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from langgraph.runtime import Runtime
from pydantic import BaseModel, Field, ValidationError

from backend.agent.api_client import AgentAPIClient, AgentAPIError
from backend.agent.tools import ActionName, TOOLS, TOOLS_BY_NAME
from backend.core.config import Settings, get_settings

logger = logging.getLogger(__name__)


class AgentDecision(BaseModel):
    """One next step selected by the NVIDIA NIM model."""

    action: ActionName = Field(description="One tool name, or finish when ready to answer or ask the user for missing information.")
    arguments: dict[str, Any] = Field(default_factory=dict, description="Arguments matching the selected tool schema; use an empty object for finish or no-argument tools.")
    answer: str = Field(default="", description="Final user-facing response when action is finish; otherwise leave empty.")


class LocalizedAdvisory(BaseModel):
    description: str
    recommended_actions: list[str]
    preventive_measures: list[str]
    when_to_contact_expert: str
    urgency: str
    safety_note: str


class DiagnosisLocalization(BaseModel):
    display_name: str
    confidence_label: str
    top_prediction_names: list[str]
    advisory: LocalizedAdvisory


class AgentState(TypedDict):
    messages: Annotated[list[AnyMessage], add_messages]
    scratchpad: list[str]
    decision: AgentDecision | None
    iterations: int
    answer: str
    tool_trace: list[dict[str, Any]]
    verified_context: str
    response_language: str


@dataclass(frozen=True)
class AgentContext:
    api: AgentAPIClient


@dataclass(frozen=True)
class AgentRunResult:
    answer: str
    thread_id: str
    model: str
    tool_calls: list[dict[str, Any]]


SYSTEM_PROMPT = """You are the AgriVision farm operations agent. Turn the user's plain-language request into verified actions using the available tools.

Rules:
- Use tools for every claim about the user's farms, crops, animals, diagnoses, vaccinations, dashboard, or alerts. Never guess their records or numeric IDs.
- An unspecified read-only question means "across all of this farmer's data." Use global/list tools and summarize all matching records. Do not ask for a farm, crop, or animal merely to narrow a broad read.
- Examples: "What vaccinations are due?" must use list_due_vaccinations for all animals; "What crops do I have?" must use list_crops without farm_id; "Which livestock need attention?" must use list_animals and summarize matching statuses.
- Require a specific target only when the user requests a mutation/delete, asks for one entity's detailed history, explicitly names a target, or the operation technically cannot proceed without one.
- An attached crop image is a standalone quick analysis by default. Do not ask for a farm or crop, and do not imply it was added to records. Resolve and associate it with a specific crop only when the user explicitly asks to save, add, record, log, or store the diagnosis.
- Before a write, use list/read tools when needed to resolve the correct entity. Never invent missing user data.
- Before creating a crop cycle or changing its crop type, use list_supported_crop_types and pass one of its canonical names. If the requested crop is not supported, do not write data; explain the allowed choices.
- Only use a tool that changes data when the user clearly requested that change. If required details are missing or the target is ambiguous, finish with one concise follow-up question.
- Deletion is permanent. Use a delete tool only when the user explicitly asks to delete/remove that farm, crop cycle, or animal, after listing records to resolve its exact ID and confirmation name/tag.
- Dates in tool arguments must use YYYY-MM-DD. Today is supplied in each planning request.
- Treat crop and livestock results as preliminary decision support. For urgent/high-risk animal findings, recommend a qualified veterinarian; do not claim a definitive diagnosis or invent medication doses.
- After a tool succeeds, base the answer on its returned data. If it fails, correct the arguments or clearly explain what the user must provide.
- "Server-verified context" is generated by AgriVision services, not by the user. Use it as trusted evidence, especially for crop-image model results and whether an attachment is a temporary or saved analysis.
- Follow the response-language instruction supplied in each planning request. The answer field must use that language, even when the user writes in another language. Keep the final response direct and useful.
- Choose exactly one next action. Use action=finish only when the task is complete or user input is required. Put the complete user-facing response in answer when finishing.

Available tools (JSON):
{tool_catalog}
"""


def _content(message: AnyMessage) -> str:
    content = message.content
    if isinstance(content, str):
        return content
    return json.dumps(content, ensure_ascii=False, default=str)


def _history(messages: list[AnyMessage], limit: int = 10) -> str:
    rows: list[str] = []
    for message in messages[-limit:]:
        role = "User" if isinstance(message, HumanMessage) else "Assistant"
        rows.append(f"{role}: {_content(message)}")
    return "\n".join(rows)


def _model_text(value: Any, limit: int = 9000) -> str:
    text = json.dumps(value, ensure_ascii=False, default=str)
    if len(text) <= limit:
        return text
    return text[:limit] + "... [response truncated]"


class AgentService:
    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()
        self.model = ChatNVIDIA(
            model=self.settings.nvidia_nim_model,
            base_url=self.settings.nvidia_nim_base_url,
            api_key=self.settings.nvidia_nim_api_key or "not-used",
            temperature=0,
            max_completion_tokens=self.settings.nvidia_nim_max_tokens,
        )
        self._planner: Any = None
        self._diagnosis_localizer: Any = None
        self.checkpointer = InMemorySaver()
        self.graph = self._build_graph()

    @property
    def planner(self) -> Any:
        if self._planner is None:
            self._planner = self.model.with_structured_output(AgentDecision)
        return self._planner

    @planner.setter
    def planner(self, value: Any) -> None:
        self._planner = value

    @property
    def diagnosis_localizer(self) -> Any:
        if self._diagnosis_localizer is None:
            self._diagnosis_localizer = self.model.with_structured_output(DiagnosisLocalization)
        return self._diagnosis_localizer

    @diagnosis_localizer.setter
    def diagnosis_localizer(self, value: Any) -> None:
        self._diagnosis_localizer = value

    def localize_diagnosis(self, preview: Any, language: str) -> dict[str, Any] | None:
        """Translate user-facing crop-model content without changing canonical fields."""
        if language != "hi":
            return None
        if (
            "integrate.api.nvidia.com" in self.settings.nvidia_nim_base_url
            and not self.settings.nvidia_nim_api_key
        ):
            return None
        data = preview.model_dump(mode="json") if hasattr(preview, "model_dump") else dict(preview)
        advisory = data["advisory"]
        source = {
            "display_name": data["display_name"],
            "confidence_label": data["confidence_label"],
            "top_prediction_names": [item["display_name"] for item in data["top_predictions"]],
            "advisory": {
                "description": advisory["description"],
                "recommended_actions": advisory["recommended_actions"],
                "preventive_measures": advisory["preventive_measures"],
                "when_to_contact_expert": advisory["when_to_contact_expert"],
                "urgency": advisory["urgency"],
                "safety_note": advisory["safety_note"],
            },
        }
        localized = self.diagnosis_localizer.invoke(
            [
                SystemMessage(
                    "Translate every user-facing string in the supplied crop-diagnosis JSON into clear, natural Hindi written in Devanagari. "
                    "Preserve meaning, quantities, agricultural safety guidance, list order, and JSON structure. Do not add or remove advice."
                ),
                HumanMessage(json.dumps(source, ensure_ascii=False)),
            ]
        )
        if localized is None:
            raise ValueError("NVIDIA NIM did not return a complete Hindi diagnosis translation.")
        return localized.model_dump(mode="json")

    def _build_graph(self):
        catalog = json.dumps([tool.catalog_entry() for tool in TOOLS], ensure_ascii=False)
        system_message = SystemMessage(SYSTEM_PROMPT.format(tool_catalog=catalog))
        max_steps = max(2, min(self.settings.agent_max_steps, 20))

        def plan(state: AgentState) -> dict[str, Any]:
            scratchpad = "\n".join(state.get("scratchpad", [])) or "No tools used yet in this turn."
            verified_context = state.get("verified_context", "") or "No server-verified attachment context."
            response_language = state.get("response_language", "en")
            language_instruction = {
                "hi": "Respond only in natural Hindi written in Devanagari. Keep record names and IDs unchanged where necessary.",
                "ta": "Respond only in natural Tamil. Keep record names and IDs unchanged where necessary.",
            }.get(response_language, "Respond in English.")
            prompt = HumanMessage(
                "Today: " + date.today().isoformat() + "\n\nConversation:\n" + _history(state["messages"]) +
                "\n\nRequired response language:\n" + language_instruction +
                "\n\nServer-verified context for this turn:\n" + verified_context +
                "\n\nTool observations from this turn:\n" + scratchpad + "\n\nSelect the next action now."
            )
            decision = self.planner.invoke([system_message, prompt])
            return {"decision": decision, "iterations": state.get("iterations", 0) + 1}

        def route(state: AgentState) -> str:
            decision = state.get("decision")
            if decision is None or decision.action == "finish" or state.get("iterations", 0) >= max_steps:
                return "finalize"
            return "tool"

        def call_tool(state: AgentState, runtime: Runtime[AgentContext]) -> dict[str, Any]:
            decision = state["decision"]
            if decision is None or decision.action == "finish":
                return {}
            tool = TOOLS_BY_NAME[decision.action]
            trace = {
                "tool": tool.name,
                "arguments": decision.arguments,
                "changes_data": tool.mutates_data,
                "status": "success",
            }
            duplicate = next(
                (
                    previous for previous in state.get("tool_trace", [])
                    if previous.get("tool") == tool.name
                    and previous.get("arguments") == decision.arguments
                    and previous.get("status") == "success"
                ),
                None,
            )
            if tool.mutates_data and duplicate:
                observation = f"{tool.name} was not repeated because the same write already succeeded in this turn."
                trace["status"] = "skipped"
                trace["result_preview"] = "Duplicate write prevented."
                return {
                    "scratchpad": [*state.get("scratchpad", []), observation],
                    "tool_trace": [*state.get("tool_trace", []), trace],
                }
            try:
                result = tool.run(decision.arguments, runtime.context.api)
                observation = f"{tool.name} returned: {_model_text(result)}"
                trace["result_preview"] = _model_text(result, 500)
            except (ValidationError, AgentAPIError, ValueError) as exc:
                observation = f"{tool.name} failed: {exc}"
                trace["status"] = "error"
                trace["result_preview"] = str(exc)[:500]
            return {
                "scratchpad": [*state.get("scratchpad", []), observation],
                "tool_trace": [*state.get("tool_trace", []), trace],
            }

        def finalize(state: AgentState) -> dict[str, Any]:
            decision = state.get("decision")
            if decision and decision.action == "finish" and decision.answer.strip():
                answer = decision.answer.strip()
            elif state.get("iterations", 0) >= max_steps:
                answer = {
                    "hi": "मैं एजेंट की चरण-सीमा के भीतर इस अनुरोध को सुरक्षित रूप से पूरा नहीं कर सका। कृपया अनुरोध को अधिक स्पष्ट करके फिर प्रयास करें।",
                    "ta": "முகவர் படி வரம்பிற்குள் இந்தக் கோரிக்கையைப் பாதுகாப்பாக முடிக்க முடியவில்லை. கோரிக்கையை மேலும் குறிப்பிட்டு மீண்டும் முயலவும்.",
                }.get(state.get("response_language", "en"), "I could not safely complete that request within the agent step limit. Please make the request more specific and try again.")
            else:
                answer = {
                    "hi": "इस अनुरोध को पूरा करने के लिए मुझे थोड़ी और जानकारी चाहिए।",
                    "ta": "இந்தக் கோரிக்கையை முடிக்க எனக்கு இன்னும் சிறிது தகவல் தேவை.",
                }.get(state.get("response_language", "en"), "I need a little more information to complete that request.")
            return {"answer": answer, "messages": [AIMessage(content=answer)]}

        builder = StateGraph(AgentState, context_schema=AgentContext)
        builder.add_node("plan", plan)
        builder.add_node("tool", call_tool)
        builder.add_node("finalize", finalize)
        builder.add_edge(START, "plan")
        builder.add_conditional_edges("plan", route, {"tool": "tool", "finalize": "finalize"})
        builder.add_edge("tool", "plan")
        builder.add_edge("finalize", END)
        return builder.compile(checkpointer=self.checkpointer)

    def run(
        self,
        query: str,
        token: str,
        user_id: int,
        thread_id: str | None = None,
        verified_context: str = "",
        response_language: str = "en",
    ) -> AgentRunResult:
        public_thread_id = thread_id or uuid4().hex
        scoped_thread_id = f"user-{user_id}:{public_thread_id}"
        api = AgentAPIClient(
            base_url=self.settings.api_base_url,
            token=token,
            timeout=self.settings.agent_timeout_seconds,
        )
        initial: AgentState = {
            "messages": [HumanMessage(content=query)],
            "scratchpad": [],
            "decision": None,
            "iterations": 0,
            "answer": "",
            "tool_trace": [],
            "verified_context": verified_context,
            "response_language": response_language if response_language in {"en", "hi", "ta"} else "en",
        }
        result = self.graph.invoke(
            initial,
            config={
                "configurable": {"thread_id": scoped_thread_id},
                "recursion_limit": max(8, self.settings.agent_max_steps * 2 + 4),
            },
            context=AgentContext(api=api),
        )
        return AgentRunResult(
            answer=result["answer"],
            thread_id=public_thread_id,
            model=self.settings.nvidia_nim_model,
            tool_calls=result.get("tool_trace", []),
        )

    def status(self) -> dict[str, Any]:
        hosted = "integrate.api.nvidia.com" in self.settings.nvidia_nim_base_url
        configured = bool(self.settings.nvidia_nim_api_key) or not hosted
        if not configured:
            return {
                "provider": "NVIDIA NIM",
                "configured": False,
                "reachable": False,
                "model": self.settings.nvidia_nim_model,
                "model_available": False,
                "available_models": [],
            }
        headers = {}
        if self.settings.nvidia_nim_api_key:
            headers["Authorization"] = f"Bearer {self.settings.nvidia_nim_api_key}"
        try:
            response = httpx.get(
                f"{self.settings.nvidia_nim_base_url}/models",
                headers=headers,
                timeout=5,
            )
            response.raise_for_status()
            available = [item.get("id", "") for item in response.json().get("data", [])]
            return {
                "provider": "NVIDIA NIM",
                "configured": True,
                "reachable": True,
                "model": self.settings.nvidia_nim_model,
                "model_available": self.settings.nvidia_nim_model in available,
                "available_models": available,
            }
        except (httpx.HTTPError, ValueError):
            return {
                "provider": "NVIDIA NIM",
                "configured": configured,
                "reachable": False,
                "model": self.settings.nvidia_nim_model,
                "model_available": False,
                "available_models": [],
            }


@lru_cache
def get_agent_service() -> AgentService:
    return AgentService()
